trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'anymodconrst001dg'
      repository: 'renovate'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
